
services:
  user:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    command: npx nodemon
    volumes:
      - ./backend:/app
      - /app/node_modules 
    depends_on:
      - mongo


  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
