
services:
  user:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI_LOCAL=mongodb://mongo:27017/library
      - SECRETKEY=jztvje%)vvmumv@tca+%=am43#53+!rutiew9gnc_4j)z807&_
    command: npm start
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - C:\Users\dhine\Documents\library-management\ngnix\ngnix.conf:/etc/nginx/conf.d/default.conf



  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    restart: always
    ports:
      - "27017:27017"


volumes:
  mongo_data:
