
services:
  user:
    build:
      context: .
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo


  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
